# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="teste2.mp3"
Content-Type: audio/mpeg

< ./teste2.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/d602886e-bb1e-4b43-a0e7-8feae9288524/transcription
Content-Type: application/json; charset=utf-8

{
    "prompt": "API, Fastfy"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "d602886e-bb1e-4b43-a0e7-8feae9288524",
    "template": "Gere um resumo sucinto da transcrição do video informada a seguir: '''{transcription}''''",
    "temperature": 0.5
}